export const STACKS = {
  'Landing Page / Marketing': {
    foundation: 'magicui + shadcn/ui',
    enhance: ['smooth-ui', 'animata', 'reactbits'],
    effects: ['shadergradient', 'particles'],
    installs: [
      'npx shadcn@latest init',
      'npx magicui-cli@latest init',
      'npm i sonner vaul tailwindcss-animate clsx tailwind-merge class-variance-authority lucide-react',
    ],
  },
  'SaaS Dashboard / App': {
    foundation: 'shadcn/ui + radix-ui',
    enhance: ['reactbits', 'animate-ui'],
    effects: [],
    installs: [
      'npx shadcn@latest init',
      'npx shadcn@latest add button card input label dialog dropdown-menu tooltip tabs badge separator sheet table',
      'npm i sonner vaul tailwindcss-animate clsx tailwind-merge class-variance-authority lucide-react',
    ],
  },
  'Portfolio / Creative': {
    foundation: 'aceternity-ui + shadcn/ui',
    enhance: ['reactbits', 'uiverse'],
    effects: ['shadergradient', 'react-three-fiber', 'liquid-logo'],
    installs: [
      'npx shadcn@latest init',
      'npm i framer-motion three @react-three/fiber @react-three/drei',
      'npm i sonner vaul tailwindcss-animate clsx tailwind-merge class-variance-authority lucide-react',
    ],
  },
  'E-commerce': {
    foundation: 'heroui + shadcn/ui',
    enhance: ['smooth-ui', 'animata'],
    effects: [],
    installs: [
      'npm i @heroui/react',
      'npx shadcn@latest init',
      'npm i sonner vaul tailwindcss-animate clsx tailwind-merge class-variance-authority lucide-react',
    ],
  },
  'AI Product': {
    foundation: 'magicui + shadcn/ui',
    enhance: ['smooth-ui', 'reactbits', 'animate-ui'],
    effects: ['shadergradient', 'particles'],
    installs: [
      'npx shadcn@latest init',
      'npx magicui-cli@latest init',
      'npm i sonner vaul tailwindcss-animate clsx tailwind-merge class-variance-authority lucide-react',
    ],
  },
  'Developer Tool': {
    foundation: 'shadcn/ui + radix-ui',
    enhance: ['reactbits'],
    effects: [],
    installs: [
      'npx shadcn@latest init',
      'npx shadcn@latest add button card input label dialog dropdown-menu tooltip tabs badge separator sheet',
      'npm i sonner vaul tailwindcss-animate clsx tailwind-merge class-variance-authority lucide-react',
    ],
  },
}

export const THEMES = {
  'Clean & Minimal': {
    primary: '#18181B',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    accent: '#2563EB',
    error: '#EF4444',
    success: '#22C55E',
    warning: '#F59E0B',
    border: '#E4E4E7',
    textPrimary: '#09090B',
    textSecondary: '#71717A',
    textMuted: '#A1A1AA',
    font: 'Inter',
    fontMono: 'JetBrains Mono',
    radius: '0.5rem',
    radiusSm: '0.25rem',
    radiusLg: '0.75rem',
    shadow: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)',
    shadowLg: '0 10px 15px rgba(0,0,0,0.1)',
    shadowGlow: 'none',
  },
  'Bold & Energetic': {
    primary: '#FF3366',
    background: '#0F0F1A',
    surface: '#1A1A2E',
    accent: '#FFCC00',
    error: '#FF4444',
    success: '#00CC88',
    warning: '#FFAA00',
    border: '#2A2A4A',
    textPrimary: '#FFFFFF',
    textSecondary: '#B0B0C8',
    textMuted: '#6B6B8D',
    font: 'Clash Display',
    fontMono: 'JetBrains Mono',
    radius: '1rem',
    radiusSm: '0.5rem',
    radiusLg: '1.5rem',
    shadow: '0 4px 16px rgba(0,0,0,0.4)',
    shadowLg: '0 20px 40px rgba(0,0,0,0.6)',
    shadowGlow: '0 0 40px rgba(255,51,102,0.3)',
  },
  'Dark & Futuristic': {
    primary: '#00D4FF',
    background: '#010409',
    surface: '#0D1117',
    accent: '#7C3AED',
    error: '#F85149',
    success: '#3FB950',
    warning: '#D29922',
    border: '#21262D',
    textPrimary: '#E6EDF3',
    textSecondary: '#8B949E',
    textMuted: '#484F58',
    font: 'Space Grotesk',
    fontMono: 'Fira Code',
    radius: '0.75rem',
    radiusSm: '0.375rem',
    radiusLg: '1rem',
    shadow: '0 4px 16px rgba(0,0,0,0.5)',
    shadowLg: '0 20px 40px rgba(0,0,0,0.7)',
    shadowGlow: '0 0 40px rgba(0,212,255,0.15)',
  },
  'Elegant & Premium': {
    primary: '#1B1B1B',
    background: '#FAF9F6',
    surface: '#FFFFFF',
    accent: '#8B7355',
    error: '#C53030',
    success: '#2F855A',
    warning: '#C05621',
    border: '#E8E4DC',
    textPrimary: '#1B1B1B',
    textSecondary: '#555555',
    textMuted: '#999999',
    font: 'Cormorant Garamond',
    fontMono: 'IBM Plex Mono',
    radius: '0.25rem',
    radiusSm: '0.125rem',
    radiusLg: '0.5rem',
    shadow: '0 1px 4px rgba(0,0,0,0.04)',
    shadowLg: '0 8px 24px rgba(0,0,0,0.08)',
    shadowGlow: 'none',
  },
  'Playful & Fun': {
    primary: '#6C5CE7',
    background: '#FFFBF5',
    surface: '#FFFFFF',
    accent: '#FF6B6B',
    error: '#E74C3C',
    success: '#00B894',
    warning: '#FDCB6E',
    border: '#E8E0D5',
    textPrimary: '#2D3436',
    textSecondary: '#636E72',
    textMuted: '#B2BEC3',
    font: 'DM Sans',
    fontMono: 'Fira Code',
    radius: '1.5rem',
    radiusSm: '0.75rem',
    radiusLg: '2rem',
    shadow: '0 4px 16px rgba(108,92,231,0.1)',
    shadowLg: '0 16px 40px rgba(108,92,231,0.2)',
    shadowGlow: '0 0 30px rgba(108,92,231,0.2)',
  },
  'Brutalist & Raw': {
    primary: '#000000',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    accent: '#FF0000',
    error: '#FF0000',
    success: '#008000',
    warning: '#FFA500',
    border: '#000000',
    textPrimary: '#000000',
    textSecondary: '#333333',
    textMuted: '#666666',
    font: 'Helvetica Neue',
    fontMono: 'Courier New',
    radius: '0',
    radiusSm: '0',
    radiusLg: '0',
    shadow: '4px 4px 0 #000000',
    shadowLg: '8px 8px 0 #000000',
    shadowGlow: 'none',
  },
}

export const MOTION = {
  'None — Static': {
    engine: 'none',
    install: null,
    maxDuration: 0,
    rule: 'Use CSS transition only for hover/focus. Duration max 200ms. No JS animation library.',
  },
  'Subtle — Micro only': {
    engine: 'motion',
    install: 'npm i motion',
    maxDuration: 300,
    rule: 'motion.dev for mount/unmount/hover only. Max 300ms. No scroll animations. No entrance animations.',
  },
  'Moderate — Transitions': {
    engine: 'motion + gsap-scroll',
    install: 'npm i motion gsap',
    maxDuration: 500,
    rule: 'motion.dev for component transitions. GSAP ScrollTrigger for scroll reveals only. Stagger max 0.1s.',
  },
  'Cinematic — Full': {
    engine: 'gsap + motion',
    install: 'npm i gsap motion @studio-freight/lenis',
    maxDuration: 1000,
    rule: 'GSAP for scroll sequences and timelines. motion.dev for React transitions. Lenis for smooth scroll. Preloader required.',
  },
}

export function selectStack({ projectType, vibe, motion }) {
  return {
    stack: STACKS[projectType],
    theme: THEMES[vibe],
    motion: MOTION[motion],
    meta: { projectType, vibe, motion },
  }
}
